### ISSUE TITLE
Certificate Fingerprint/Hashes do not match that of browsers

### ISSUE THREAD

**Issue by 0xDiBa** [mozilla/TLS-Observer#22]

**Comment by 0xDiBa** [comment]
2a435d88df2775627565ef7aadf2cba7b41c7cc0

**Comment by jvehent** [comment]
:+1: ! that is awesome!

On April 10, 2015 6:57:25 PM EDT, Dimitris Bachtis <notifications@github.com> wrote:
>2a435d88df2775627565ef7aadf2cba7b41c7cc0
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mozilla/TLS-Observer/issues/22#issuecomment-91712123

-- 
sent from mobile
