### ISSUE TITLE
tlsAnalyzer does not declare its queue

### ISSUE THREAD

**Issue by jvehent** [mozilla/TLS-Observer#25]
This call should be preceded by a queue declaration:
https://github.com/mozilla/TLS-Observer/blob/master/src/tlsAnalyser/tlsAnalyser.go#L239
(returned errors should be checked as well).

**Comment by 0xDiBa** [comment]
The queue is automatically declared by the amqpmodule wrapper I have built.
Don't know if its a good way to go, just wanted to take out logic from the
analysers.

You are absolutely right about the error handling.

Thanks for checking out the code ;) .

**Comment by jvehent** [comment]
Ha, so, I think if you just add the queue name to this call instead of `""` it will work :palm_tree: 
https://github.com/mozilla/TLS-Observer/blob/master/src/modules/amqpmodule/amqpmodule.go#L128

**Comment by 0xDiBa** [comment]
Oooops....

**Comment by 0xDiBa** [comment]
Relates to issue #27
