### ISSUE TITLE
{cert,tls}Analyzer publication to worker.{cert,tls}

### ISSUE THREAD

**Issue by jvehent** [mozilla/TLS-Observer#30]
The main analyzers should published analyzed results into a rabbitmq worker queues, where task specific workers can process and alert.

**Comment by 0xDiBa** [comment]
cd9503b2a6db8085c648798d98c26c01fa08bda8 
Might have to consider the worker queues' names.

**Comment by jvehent** [comment]
Well that was easy :) :+1:
