### ISSUE TITLE
Implement syslog logging

### ISSUE THREAD

**Issue by jvehent** [mozilla/TLS-Observer#38]
Analyzers, retrievers and workers should log their activity to syslog, in the DAEMON facility.

**Comment by jvehent** [comment]
This is a requirement for proper production deployment. Note that we might replace Syslog with heka in production, but it doesn't change the code on the observatory's side.

**Comment by jvehent** [comment]
Take a look at https://github.com/Sirupsen/logrus

**Comment by 0xDiBa** [comment]
d47667e973b6b53d8cc60728229bdf169acde361
