### ISSUE TITLE
AWS SQS/SNS Integration

### ISSUE THREAD

**Issue by 0xDiBa** [mozilla/TLS-Observer#39]
Create a message broker module that utilises SQS/SNS.

**Comment by jvehent** [comment]
As discussed, the integration should not replace the existing RabbitMQ model, to allow local dev to continue to happen.

**Comment by jvehent** [comment]
For ref: https://github.com/aws/aws-sdk-go
Some examples of using this API at https://github.com/mozilla-services/reaper

**Comment by jvehent** [comment]
New architecture doesn't use queue anymore.

**Comment by jvehent** [comment]
@0xDiBa : looks like the scanner still depends on consume incoming scans from rabbitmq. I thought that was gone, so I'm a bit confused. What's up with that? https://github.com/mozilla/tls-observatory/blob/master/tlsObserver.go#L67-L77

**Comment by 0xDiBa** [comment]
I have left it in until I manage to make the new postgres notify solution absolutely consistent and reliable. I am testing solutions now. It has something to do with the behaviour of SELECT ... FOR UPDATE. I hope to get it working consistently today or tomorrow.

**Comment by jvehent** [comment]
Does the current code work with a single worker? If so, let's remove rabbitmq support asap so I can deploy and test without it, and continue working on the select for update bit.

**Comment by 0xDiBa** [comment]
I created a patch in your pull request.
Postgres messaging works nicely now.
It seems that at my latest test I had forgotten to rollback some transactions and that was why many workers listeners got stuck.

It should now work without problems even with many different scanners spanning multiple executables.

Fingers Crossed ;)
