### ISSUE TITLE
Postgres storage/quering module

### ISSUE THREAD

**Issue by 0xDiBa** [mozilla/TLS-Observer#40]
Create a module that interacts with PostgreSQL as a backend storage.

**Comment by jvehent** [comment]
All fields that are currently statically defined in the `certificate` and `ciphersuite` documents should become columns in the relational database. We should have uniqueness indexes on the certificate IDs.

The DB should be relational, meaning the we should have a simple way to query all the children of a given intermediate or root CA (maybe with a `isChildrenOf` table, or something similar).

AWS RDS now supports Postgres 9.4, so we can use the `jsonb` data type and indexes inside of JSON structures, but I would prefer to keep JSON columns down to a minimum and move as much as possible into statically defined columns, for ease of querying.

Can you please post a entity-relation diagram before you start coding?

**Comment by jvehent** [comment]
zmap has a DB schema we could potentially reuse https://scans.io/data/umich/https/schema.txt

**Comment by jvehent** [comment]
Implemented.
