### ISSUE TITLE
Architectural restructuring

### ISSUE THREAD

**Issue by 0xDiBa** [mozilla/TLS-Observer#42]
Redesign and rethink architectural decisions in order to provide the API required by Minion.

**Comment by jvehent** [comment]
Could you get into details of what exactly should be rearchitected?

**Comment by 0xDiBa** [comment]
First of all we'll have to make changes to the more specific workers ( or to the base module that is going to be used by future workers ) so that they return results to the API and store to the DB ( current specific workers are just made to publish to MozDef ). 

Also we will have to decide if every worker is going to run on its own and just listen to specific queues ( which is pretty near to what we were doing up until now ) or we will have one off workers which will be spawned by the handling part of the API. 

I am sure that other stuff ( regarding the API or the internal architecture ) will come up if we put some deeper thought into in ;) .

**Comment by jvehent** [comment]
Implemented.
